version: "3"

services:
  consumer:
    image: bitnami/python:3.9
    command: "sh -c 'pip install -r requirements.txt && python consumer.py'"
    networks:
      - kafkanet
    environment:
      TOPICS: orders
      GROUP_ID: orders-group
      BOOTSTRAP_SERVERS: kafka:9092
      OFFSET_STR: "2023-01-06T19:00:00"
      TZ: Australia/Sydney
    volumes:
      - .:/app

networks:
  kafkanet:
    external: true
    name: kafka-network
