version: "3.5"

services:
  kpow: # https://docs.kpow.io/ce/
    image: factorhouse/kpow-ce:91.2.1
    container_name: kpow
    ports:
      - "3000:3000"
    networks:
      - kafkanet
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
      BOOTSTRAP: kafka-0:9092,kafka-1:9092,kafka-2:9092
      SCHEMA_REGISTRY_ARN: $SCHEMA_REGISTRY_ARN
      SCHEMA_REGISTRY_REGION: $AWS_DEFAULT_REGION
      # CONNECT_REST_URL: http://connect:8083
      # SCHEMA_REGISTRY_URL: http://schema:8081
      # SCHEMA_REGISTRY_AUTH: USER_INFO
      # SCHEMA_REGISTRY_USER: admin
      # SCHEMA_REGISTRY_PASSWORD: admin
      # AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      # AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      # AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN

    volumes:
      - ../misc:/glue-serde

networks:
  kafkanet:
    external: true
    name: kafka-network
