version: "3.5"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181"
    networks:
      - kafkanet
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper
  kafka:
    image: docker.io/bitnami/kafka:3.3
    container_name: kafka
    expose:
      - 9092
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    networks:
      - kafkanet
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=0
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=SSL:SSL,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=SSL://:9093,PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=SSL://kafka:9093,PLAINTEXT://kafka:9092
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/bitnami/kafka/config/certs/kafka.keystore.jks
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=secret
      - KAFKA_CFG_SSL_KEY_PASSWORD=secret
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/bitnami/kafka/config/certs/kafka.truststore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=secret
      - KAFKA_CFG_SSL_CLIENT_AUTH=required
    volumes:
      - kafka_data:/bitnami/kafka
      - ./security/certs/client.keystore.jks:/bitnami/kafka/config/certs/kafka.keystore.jks:ro
      # - ./security/keystore/kafka.server.keystore.jks:/bitnami/kafka/config/certs/kafka.keystore.jks:ro
      - ./security/truststore/kafka.truststore.jks:/bitnami/kafka/config/certs/kafka.truststore.jks:ro
    depends_on:
      - zookeeper

networks:
  kafkanet:
    name: kafka-network

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
