version: "3.5"

services:
  app:
    image: bitnami/python:3.9
    command: "sh -c 'pip install -r requirements.txt && python consumer.py'"
    networks:
      - kafkanet
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
      BOOTSTRAP_SERVERS: kafka-0:9092,kafka-1:9092,kafka-2:9092
      TOPIC_NAME: orders
      GROUP_ID: orders-group
      REGISTRY_NAME: online-order
      TZ: Australia/Sydney
    volumes:
      - ./consumer.py:/app/consumer.py
      - ./requirements.txt:/app/requirements.txt

networks:
  kafkanet:
    external: true
    name: kafka-network
