version: "3.5"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181"
    networks:
      - kafkanet
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./.bitnami/zookeeper/data:/bitnami/zookeeper/data
  kafka-0:
    image: docker.io/bitnami/kafka:3.3
    container_name: kafka-0
    ports:
      - "9092"
    networks:
      - kafkanet
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=0
    volumes:
      - ./.bitnami/kafka_0/data:/bitnami/kafka/data
      - ./.bitnami/kafka_0/logs:/opt/bitnami/kafka/logs
    depends_on:
      - zookeeper
  kafka-1:
    image: docker.io/bitnami/kafka:3.3
    container_name: kafka-1
    ports:
      - "9092"
    networks:
      - kafkanet
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=1
    volumes:
      - ./.bitnami/kafka_1/data:/bitnami/kafka/data
      - ./.bitnami/kafka_1/logs:/opt/bitnami/kafka/logs
    depends_on:
      - zookeeper
  kafka-2:
    image: docker.io/bitnami/kafka:3.3
    container_name: kafka-2
    ports:
      - "9092"
    networks:
      - kafkanet
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=2
    volumes:
      - ./.bitnami/kafka_2/data:/bitnami/kafka/data
      - ./.bitnami/kafka_2/logs:/opt/bitnami/kafka/logs
    depends_on:
      - zookeeper
  kafka-ui:
    image: provectuslabs/kafka-ui:master
    container_name: kafka-ui
    ports:
      - "8080:8080"
    networks:
      - kafkanet
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-0:9092,kafka-1:9092,kafka-2:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - zookeeper
      - kafka-0
      - kafka-1
      - kafka-2

networks:
  kafkanet:
    name: kafka-network
